# Generated by Django 5.1.6 on 2025-09-04 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticating', '0002_remove_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='user.jpg', upload_to='profile_pics'),
        ),
    ]
